@startuml
== 司机查询防疫信息 ==
客户端 -> dic: ocr.msg

activate dic

dic -> driver_svc: 查询司机防疫信息(driver.health.check)

driver_svc -> backend: 开城配置
alt 未开城
driver_svc -> dic: 不需要展示banner位
end
driver_svc -> mysql: 查询司机今天是否有防疫记录(xl_driver_ocr)
alt 已有防疫记录
driver_svc -> dic: 不需要展示banner位
end

driver_svc -> dic: 需要展示banner位

dic -> 客户端: 司机状态信息
deactivate dic

@enduml

