@startuml
== 司机h5提交防疫记录 ==

dappweb -> driver_svc: driver.ocr.record.today\n查询今日防疫提交记录

alt 未提交过
dappweb -> driver_svc: driver.ocr.upload\n防疫图片list+防疫验证总状态

driver_svc -> mysql: xl_driver_ocr_image/xl_driver_ocr_status表
end
@enduml

